GET http://localhost:4000/customers

###

GET http://localhost:4000/employees

###

GET http://localhost:4000/products?perPage=20

###

GET http://localhost:4000/business-entities

###
GET http://localhost:4000/order-details/2

###
GET http://localhost:4000/orders

###
GET http://localhost:4000/orders/2

###
 
GET http://localhost:4000/businessentities/max-price

###

GET http://localhost:4000/customer-orders

###

